codecov:
  require_ci_to_pass: true
coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 85
        threshold: 2
    patch:
      default:
        target: 85
comment:
  layout: reach, diff, flags, files
  require_changes: false